//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fig1
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string paciente1 { get; set; }
        public string especie { get; set; }
        public string raca { get; set; }
        public Nullable<int> idade { get; set; }
        public string sexo { get; set; }
        public string nometutor { get; set; }
        public string emailtutor { get; set; }
        public string telefonetutor { get; set; }
        public string nomeveterinario { get; set; }
        public string emailveterinario { get; set; }
        public string telefoneveterinario { get; set; }
    }
}
